
export const MOCK_STATEMENTS = [
  {
    id: 1,   // stationId
    stationName: 'Test Station',
    isBalanced: true,
    expectedIncome: 100.9,
    expectedOutcome: 100.0,
    actualIncome: 100.9,
    actualOutcome: 100.0,
    discount: 0.9,
    franchiseeId: 1,
    franchiseeName: 'Test',
    downloadUrl: 'xxxxxxxxxx',
    date: '2017-07-02',
  },
  {
    id: 2,   // stationId
    stationName: 'Test Station',
    isBalanced: true,
    expectedIncome: 100.9,
    expectedOutcome: 100.0,
    actualIncome: 100.9,
    actualOutcome: 100.0,
    discount: 0.9,
    franchiseeId: 1,
    franchiseeName: 'Test',
    downloadUrl: 'xxxxxxxxxx',
    date: '2017-07-02',
  },
  {
    id: 7,   // stationId
    stationName: 'Test Station',
    isBalanced: true,
    expectedIncome: 100.9,
    expectedOutcome: 100.0,
    actualIncome: 100.9,
    actualOutcome: 100.0,
    discount: 0.9,
    franchiseeId: 1,
    franchiseeName: 'Test',
    downloadUrl: 'xxxxxxxxxx',
    date: '2017-07-02',
  },
  {
    id: 3,   // stationId
    stationName: 'Test Station',
    isBalanced: true,
    expectedIncome: 100.9,
    expectedOutcome: 100.0,
    actualIncome: 100.9,
    actualOutcome: 100.0,
    discount: 0.9,
    franchiseeId: 1,
    franchiseeName: 'Test',
    downloadUrl: 'xxxxxxxxxx',
    date: '2017-07-02',
  },
  {
    id: 4,   // stationId
    stationName: 'Test Station',
    isBalanced: true,
    expectedIncome: 100.9,
    expectedOutcome: 100.0,
    actualIncome: 100.9,
    actualOutcome: 100.0,
    discount: 0.9,
    franchiseeId: 1,
    franchiseeName: 'Test',
    downloadUrl: 'xxxxxxxxxx',
    date: '2017-07-02',
  },
  {
    id: 5,   // stationId
    stationName: 'Test Station',
    isBalanced: true,
    expectedIncome: 100.9,
    expectedOutcome: 100.0,
    actualIncome: 100.9,
    actualOutcome: 100.0,
    discount: 0.9,
    franchiseeId: 1,
    franchiseeName: 'Test',
    downloadUrl: 'xxxxxxxxxx',
    date: '2017-07-02',
  },
];
